### ISSUE TITLE
Lighting issues caused by road generation using the bridge template.

### ISSUE THREAD

**Issue by mibby** [IntellectualSites/PlotSquared#1378]
PlotSquared dev 357
FAWE dev 332
Paper dev 881 (Spigot 1.10.2)

Settings
http://paste.ubuntu.com/23253696/

FAWE Config
http://paste.ubuntu.com/23253717/

Generated a fresh new world using the bridge template. Plagued with lighting bugs.
![link](http://i.imgur.com/XResL8t.png)
![link2](http://i.imgur.com/Qs1i6YX.jpg)

**Comment by boy0001** [comment]
Nothing related to FAWE, that's a spigot bug, which was supposedly marked as fixed:
https://hub.spigotmc.org/jira/browse/SPIGOT-1753

**Comment by mibby** [comment]
So no way to prevent lighting issues when the road terrain is generated via a schematic? :( Rather not have to go around the entire world and spam ```//fixlighting``` until everything is normalized. Might as well just keep a flat road.

**Comment by boy0001** [comment]
`/2 regenallroads`, but it's something that should be fixed in spigot.

**Comment by chamunks** [comment]
I would even suggest you check out Paper instead of Spigot I believe its probably got some fixes for stuff that spigot generally leaves out.

**Comment by mibby** [comment]
@chamunks 

>I would even suggest you check out Paper instead of Spigot

---

>Paper dev 881 (Spigot 1.10.2)

Perhaps @Zbob750 or @aikar can look into the problem as to why chunk lighting is broken upstream in Spigot / Paper using the ChunkData object.

**Comment by AeSix** [comment]
Is this still an issue with newer builds? I've not seen major lighting issues in P2 in quite a while.

**Comment by TheManchineel** [comment]
This bug is still present 1.15.2, latest PaperMC #133
![2020-03-13_14 20 50](https://user-images.githubusercontent.com/37479927/76624855-5cee9380-6536-11ea-82ba-16da2259c542.png)
