### ISSUE TITLE
Hopper, Furnace and Brewing stand are freeze

### ISSUE THREAD

**Issue by AlansS53** [IntellectualSites/PlotSquared#2035]
**Duplicate without response:**
https://github.com/IntellectualSites/PlotSquared/issues/1716

**Debug paste link:** 
This shows an error in my console: https://pastebin.com/3As1Duzt

**Description of the problem:** 
When a player uses the command /p dispose all the beacons, furnace, hopper and brewing booth in the PlotWorld world they freeze and stop working. Furnace and brewing stand stop cooking and the hoppers do not move or claim items.

**How to replicate:** 
Here is a video that shows it...
https://www.youtube.com/watch?v=9D7inwYYXiw&feature=youtu.be

**Checklist**:

- [x] I included a `/plot debugpaste` link 
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of PlotSquared
- [x] I Made sure the bug/error is not caused by any other plugin

**Comment by Weark** [comment]
Not only with the "/ p dispose"
Well, I've removed that permission and there's something else they're doing to make it all freeze too.

**Comment by boy0001** [comment]
A temporary fix would be to install FAWE and have it handle the plot clearing.

**Comment by alexmarkey** [comment]
Been waiting since last year for a fix on this!

**Comment by AlansS53** [comment]
Edit, this also happens with beacons

**Comment by zombachu** [comment]
Someone can correct me if I'm wrong but I believe this issue is connected to what Aikar described in his blog post [here](https://aikar.co/2015/10/08/spigot-tick-limiter-dont-use-max-tick-time/). At least, effective disabling max-tick-time has fixed tile entities freezing from large world operations on my server.

**Comment by AlansS53** [comment]
@zombachu How can I disable max-tick-time? I would like to try it.

**Comment by zombachu** [comment]
@AlansS53 It’s In your spigot.yml

**Comment by AlansS53** [comment]
@zombachu I know, but I have not found how to disable it in the spigot tutorial, I suppose it will be placing the values in 0?

**Comment by zombachu** [comment]
@AlansS53 Set it to something high, like 10000

**Comment by theJ3H** [comment]
I'm having the same issue.
Setting max-tick-time to 10000 did nothing for me. I'm using the latest version 1.8 of tacospigot.

I installed FAWE and that did the trick, for now at least.

I tried to update to 1.9 and couldnt reproduce the issue on a 1.9 server.
Maybe this is related to https://hub.spigotmc.org/jira/browse/SPIGOT-1746 , which was fixed in 1.9?

**Comment by AlansS53** [comment]
Hello, sorry for the delay, as it says @ theJ3H place "max-tick-time" in 10000 or more does not solve the problem, so far it continues to happen only with the command / p dispose.

**Comment by AlansS53** [comment]
I add: This only happens inside the plots, all tile entity in the street works normally.

**Comment by AeSix** [comment]
@AlansS53  can you give us a /plot debugpaste please
More information is needed.  Though, you should understand that development focus is currently for 1.13, however if it's a serious bug or easy fix the devs may choose to fix it. 

Additionally, make sure your using the newest build for your Minecraft version, both P2 and FAWE. 

If the issue is solved, please consider closing the ticket.  Thank you :)

**Comment by AeSix** [comment]
closing due to no response. 
If this is still an issue, reopen.
