### ISSUE TITLE
Merged plots are unlinked and unclaimed after a few hours

### ISSUE THREAD

**Issue by MonkvanNederland** [IntellectualSites/PlotSquared#801]
Hi, we have a big problem with merging plots. It's installed on a brand new map with the custom PlotSquared generator. When merging plots, sometimes parts of te road or wall stays on the plots.
https://www.dropbox.com/s/t6yofj058kox0r5/2015-12-21_20.29.29.png?dl=0

Sadly the user reclaimed the plots before i could make a screenshot of the crossroads in the merged plots. They also cannot break the wall blocks as shown in the screenshot.

The second problem which is huge, is that merged plots get unlinked by them selves after a few hours with no reason or error. For example: I claim 4 plots en merge them with auto merge into 1 big plot. After a few hours the plots get unlinked, and 3 are unclaimed! Which means other players can claim them and destroy the buildings and steal their items. Only 1 plot remains claimed.

Let me know what information you need to fix this problem. We use this function for donor players.

**Comment by i9hdkill** [comment]
Is your database setup correct? any errors in your server log?

**Comment by MonkvanNederland** [comment]
We're using the standard .db database. Here is the PlotSquared folder:
https://www.dropbox.com/s/xq753qppc2wdrak/PlotSquared.tar.gz?dl=0

There are no errors in the console. Here is the debugpaste:
http://hastebin.com/uduvuxikuv

**Comment by MonkvanNederland** [comment]
Ticket #802 from DoraKlikOpDora reports a similar problem. We also regenerated our roads.

**Comment by johandrex** [comment]
I'm having the same issue.. Hasn't happened before..

**Comment by johandrex** [comment]
This have to be fixed ASAP.

**Comment by johandrex** [comment]
@boy0001 emergency

**Comment by xion87** [comment]
i confirm the issue, happening also to my user....

**Comment by xion87** [comment]
and yes i do road regeneration.... before

**Comment by coelho** [comment]
I can also confirm this is an issue.

**Comment by zzkanezz2** [comment]
Should I be worried about this, we just updated and a ton of large plot builds have already been merged

**Comment by johandrex** [comment]
@zzkanezz2 You should unmerge them until this is fixed, otherwise the buildings will be destroyed within a few days randomly.

**Comment by MonkvanNederland** [comment]
I just tried again and watched closely what happend. There are NO problems if you do not use custom road schematics. After "/plots regenallroads" it goes wrong after a few hours. Merged plots get unlinked and unclaimed. Only one plot of the previous merged plots remains claimed. At this point other players CAN claim the unclaimed merged plots. After a server restart i got the message that those plots are already claimed when you try to claim them, but "/plots info" says otherwise (no owner). After claiming and a second restart, the previous merged plots suddenly has 2 owners! The previous owner of the merged plots, and the new owner (in this case me). After unclaiming the plots you can reclaim them, and then there is 1 owner as it should be. But the problem remains. Plots still get unmerged and unclaimed. So whatever you do, do NOT use "/plots regenallroads" and do NOT use "/plot createroadschematic"! Please fix this, we have to much plots occupied with donor players to start a new map without custom roads.

**Comment by johandrex** [comment]
We should send him a PM on spigot to raise awareness to this issue.

**Comment by Sauilitired** [comment]
This is literally the weirdest problem I've ever seen reported on here. Sadly, I don't know nearly enough about that part of the plugin to help fix the problem. However, I can always speculate. Gathering some `/plot debugpaste` samples could be useful, so if you've encountered this, feel free to send some.

**Comment by johandrex** [comment]
http://pastebin.com/MBsWeMfE

**Comment by MonkvanNederland** [comment]
Now intel Sir! We tried some tests with merging. 1 group near the center where plots are claimed using "/plot claim auto", and a 2nd group far away where the auto claiming does not yet claim plots. After a few hours the merged plots are unclaimed and unlinked as mentioned before, but you cannot manually claim them (non-admins). If the "/plot claim auto" claims one of those unlinked plots, the player get's the plot, but cannot do anything. He cannot build or use any plot commands on that plot, including "/plot delete", so he is stuck and cannot claim a new plot (non-donors can only have 1 plot on our server). 

The 2nd group - which is not claimed by the automatic plot claiming - was also unlinked and unclaimed. Here is the interesting part, after a server restart the un-merged plot are back merged again. The previously unlinked plot claimed by the player using "/plot auto claim" has now 2 owners. But the newest owner still cannot build or use any plot commands on the plot. The second group is working fine again, until the bug reappears.

We are running 2 plot worlds. The old world was converted from Plotme, and does not have this problem (we did not use a road generator here). I tried solving it in the new world by syncing the road-schematic with the world value in the config file, and then regenallroads again so all roads are the same as in the config file. Then i deleted the road-schematic and restarted the server. After trying a few claiming/unclaiming and merging/unlinking a few plots, the roads and plots regenerate as it supposed to do. But still after a few hours the plots on the new world keep getting unlinked and unclaimed. So a restart fixes it, but there is something that triggers the problem. Could it be a combination of the road-regenation and the automatic plot claiming?

Good luck guys :)

**Comment by Pangamma** [comment]
How does a bug like this even happen...

**Comment by Johandrex** [comment]
I need this fixed ASAP, if you fix it within 48 hours I'll donate 20 USD.

**Comment by Sauilitired** [comment]
DebugRoadRegen.java
```java
manager.createRoadEast(plotworld, plot);
manager.createRoadSouth(plotworld, plot);
manager.createRoadSouthEast(plotworld, plot);
```

These lines seem to cause merged plots to unmerge. My guess is that the algorithms doesn't count in the merged plot size differences, for some reason. However, I'm clueless. @boy0001, halp plz.

**Comment by coelho** [comment]
I'll join @Johandrex and pledge 20 USD towards this bug as well :+1:

**Comment by xion87** [comment]
also with regenroad 2 border of plot get to original one... can be related?

**Comment by MattBDev** [comment]
I'm looking at the code to see if I can also find a solution.

**Comment by Johandrex** [comment]
Any updates?..

**Comment by MattBDev** [comment]
@Johandrex I have a few questions so I can continue to look into this. Does this occur even after the server reboots without any information in the console? Does the data in the database change and mark the plot as unmerged? What spigot version are you using?

**Comment by Johandrex** [comment]
They're unlinked randomly

**Comment by boy0001** [comment]
Would you like to come on IRC and troubleshoot right now?
[link](http://webchat.esper.net/?nick=&channels=IntellectualCrafters&fg_color=000&fg_sec_color=000&bg_color=FFF)

**Comment by gameplayerhd** [comment]
I have the same issue. Parts of a merged plot gets unlinked and claimed by somebody else. Seems random on our server

**Comment by Johandrex** [comment]
Still having the bug.

**Comment by MattBDev** [comment]
@Johandrex I'm still looking into it. This bug is extremely difficult to pinpoint. Do you know how to look inside your database? If you do, check to see if the plots being unclaimed are still in the database.

**Comment by Johandrex** [comment]
I don't know how to look into my sql database.

**Comment by MattBDev** [comment]
If anyone else having this issue knows how to check their database. Please let me know if the plots are still in the database when they are unclaimed.

**Comment by boy0001** [comment]
@MattBDev 
[PlotSquared.zip](https://github.com/IntellectualSites/PlotSquared/files/130872/PlotSquared.zip)

**Comment by gameplayerhd** [comment]
@MattBDev I'm waiting for a case to look at the database. The problem is when I find out it's already claimed by a new player.

**Comment by MattBDev** [comment]
@gameplayerhd Once you notice something in the database, let me know.

**Comment by gameplayerhd** [comment]
@MattBDev Was extremely hard for me to find unlinked plots without it already being claimed again.

I did find this on the forums that might pinpoint the problem? https://www.spigotmc.org/threads/plotsquared.29970/page-128#post-1314591

He mentions that /plot visit has something to do with it.

Thanks

**Comment by gameplayerhd** [comment]
Might have found the issue from the logs:

@MattBDev http://pastebin.com/uB3Hk8KG mentions duplicated plots?

**Comment by SliderKP** [comment]
any solution to this bug/problem?

**Comment by Sauilitired** [comment]
@SliderKP clearly not, just read previous comments.

**Comment by Johandrex** [comment]
It has been two months now... When will this be fixed?

**Comment by MattBDev** [comment]
@Johandrex It is hard to fix a bug that the developers can't reproduce. @boy0001 may have a 3.3.0 build that we can use to see if this bug is fixed.

**Comment by boy0001** [comment]
https://github.com/IntellectualSites/PlotSquared/blob/master/target/PlotSquared-Bukkit.jar

**Comment by MattBDev** [comment]
@SliderKP @Johandrex @gameplayerhd @MonkvanNederland @xion87 Is this issue fixed with the jar above?

**Comment by Johandrex** [comment]
Tested a bit but for some reason players could use tnt to explode other players plots, except their own.

**Comment by MattBDev** [comment]
@Johandrex Unrelated to the issue we are trying to fix at the moment. The issue we want to fix in this ticket is the merging. We need a confirmation on this issue first before we move on to that.

**Comment by xion87** [comment]
not sure, if is fixed because it need a live player server for see if it bugs, and is hard to test by myself

**Comment by MonkvanNederland** [comment]
Tested for 2 days now, the bug is still there, problem is not solved.

Plots keep being unclaimed and unlinked after a few hours.

**Comment by xion87** [comment]
maybe it have to do with unloaded chunks?

**Comment by MattBDev** [comment]
Can someone here please test with 3.3.3?

**Comment by manuelgu** [comment]
Running in production and have not encountered any problems. Then again, I only have a couple plots merged.

**Comment by MonkvanNederland** [comment]
Running tests for a couple of days now, all is going well. Tomorrow we're releasing it again for our players. I will post any errors about the merging/unclaiming if there are any. If i do not post anu message within 7 days, then we had no errors.

**Comment by hyWse** [comment]
same problem after more than 3 years with the latest version.

**Comment by AeSix** [comment]
odd. I've got multiple merged plots that have been for 18-24 months... multiple versions of P2.

**Comment by hyWse** [comment]
Perhaps it helps that I use custom Roads (schematics).

Brand new server / installation

**Comment by AeSix** [comment]
Same. they're not overly fancy roads, but are schems none the less. 2 servers using P2 with merged plots.

**Comment by dordsor21** [comment]
I feel like it's an issue with world-saving. Are the plots definitely unmerged, or is the road just regenerated? Sit between the two plots (on the road) and run /plot info,

**Comment by hyWse** [comment]
No roads have been generated. They were simply unlinked.

**Comment by dordsor21** [comment]
Are you using SQLite or MySQL?

**Comment by hyWse** [comment]
we tried both. MySQL and SQLite

**Comment by dordsor21** [comment]
Can you provide a debugpaste?

**Comment by hyWse** [comment]
https://hastebin.com/nizigegehi

**Comment by dordsor21** [comment]
What's your storage.yml in the settings folder?

**Comment by hyWse** [comment]
```
prefix: ''

# SQLite section
sqlite:
  # Should SQLite be used?
  use: true
  # The file to use
  db: "storage"

# MySQL section
mysql:
  # Should MySQL be used?
  use: false
```
