### ISSUE TITLE
Plot Cluster Errors

### ISSUE THREAD

**Issue by astr1al** [IntellectualSites/PlotSquared#980]
Debug Paste
http://hastebin.com/ajevefixon

Here's the first error that pops up when enabling P2
http://pastebin.com/mqzBJUJ3

Later on when the plugin loads it sends this error
http://pastebin.com/5qRFiGBb

I am running on Spigot 1.9, this wasn't an issue on 1.8.9. Guessing its something to do with - values in chunk id's in the plot configs.

**How to replicate**:

Make sure you've completed the following steps (put an X between of brackets):
- [x] Include `/plot debugpaste`
- [X] Made sure there aren't duplicates of this report [(Use Search)](https://github.com/IntellectualSites/PlotSquared/issues)
- [X] Made sure you're using an updated version of PlotSquared
- [X] Made sure the bug/error isn't caused by any other plugin

**Comment by MattBDev** [comment]
Fixed in this commit a few days ago 3fb64d9811d041f3c4d605baf67a51e6c46e1a86

**Comment by astr1al** [comment]
I still have this error w/ the latest build. :/

**Comment by MattBDev** [comment]
@astr1al can you produce a new `/plots debugpaste` link when using the dev build where it should have been fixed?

**Comment by boy0001** [comment]
@MattBDev it would be the same error.

The cluster creation as described on the wiki was removed in favour of the '/plot area' command. It's still an error, as trying to create a cluster in a non plot world should print a usage message.

Anyway, the new syntax is '/plot area create type=<terrain> terrain=0 size=<size>'

Terrain 0 would be flat plots. I'll update the wiki/plugin when I get home

**Comment by astr1al** [comment]
@MattBDev  Here's a /plots debug from build #26 http://hastebin.com/ekoyirozet

**Comment by astr1al** [comment]
Fixed by regenerating a new config, then re-adding cluster data to bottom of config.

**Comment by MattBDev** [comment]
@astr1al can I see you config now so I can just compare it to the old one you had?

**Comment by astr1al** [comment]
@MattBDev Here ya go http://pastebin.com/cdMYB5zP
